# For generic x86_64 architecture.
[x86-64-unknown-linux-gnu]
rustflags = [
    "-C",
    "target-cpu=x86-64-v4",
    "-C",
    "target-feature=+fma,+avx2,+avx",
    "-C",
    "llvm-args=-ffast-math",
    "-C",
    "opt-level=3",
]

# Use +avx512 to enable avx512.
# https://rust-lang.github.io/packed_simd/perf-guide/target-feature/rustflags.html
# rustflags = ["-C", "target-cpu=native", "-C", "target-feature=+avx,+fma"]
